package com.deppon.test05.entity;

import java.math.BigDecimal;
import java.util.Date;

public class CustomerEntity extends CustomerEntityKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.Name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.NameSpell
     *
     * @mbg.generated
     */
    private String namespell;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.CustomerNo
     *
     * @mbg.generated
     */
    private String customerno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.Address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.Tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.Level
     *
     * @mbg.generated
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.Industry
     *
     * @mbg.generated
     */
    private String industry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.SubIndustry
     *
     * @mbg.generated
     */
    private String subindustry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.Source
     *
     * @mbg.generated
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.Remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.OwnerID
     *
     * @mbg.generated
     */
    private Integer ownerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.HighSeasID
     *
     * @mbg.generated
     */
    private String highseasid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.ClaimTime
     *
     * @mbg.generated
     */
    private Date claimtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.ExpireTime
     *
     * @mbg.generated
     */
    private Date expiretime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.JoinHighSeasTime
     *
     * @mbg.generated
     */
    private Date joinhighseastime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.Status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.ResaleCount
     *
     * @mbg.generated
     */
    private Integer resalecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.CreatorID
     *
     * @mbg.generated
     */
    private Integer creatorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.CreateTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.UpdatorID
     *
     * @mbg.generated
     */
    private Integer updatorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.UpdateTime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.FilingCheckerID
     *
     * @mbg.generated
     */
    private Integer filingcheckerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.DealStatus
     *
     * @mbg.generated
     */
    private Integer dealstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.TradeTotalMoney
     *
     * @mbg.generated
     */
    private BigDecimal tradetotalmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.PaymentTotalMoney
     *
     * @mbg.generated
     */
    private BigDecimal paymenttotalmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.RefundTotalMoney
     *
     * @mbg.generated
     */
    private BigDecimal refundtotalmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.TakeBackTime
     *
     * @mbg.generated
     */
    private Date takebacktime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.DealTime
     *
     * @mbg.generated
     */
    private Date dealtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.OldOwnerID
     *
     * @mbg.generated
     */
    private Integer oldownerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.OpportunityTotalMoney
     *
     * @mbg.generated
     */
    private BigDecimal opportunitytotalmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.LastFollowTime
     *
     * @mbg.generated
     */
    private Date lastfollowtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.InputFieldNumber
     *
     * @mbg.generated
     */
    private Integer inputfieldnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.LastTradeMoney
     *
     * @mbg.generated
     */
    private BigDecimal lasttrademoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.IndustryName
     *
     * @mbg.generated
     */
    private String industryname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.OwnerChangedTime
     *
     * @mbg.generated
     */
    private Date ownerchangedtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.HouseNo
     *
     * @mbg.generated
     */
    private String houseno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.Area
     *
     * @mbg.generated
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.AreaFullName
     *
     * @mbg.generated
     */
    private String areafullname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.IsDeleted
     *
     * @mbg.generated
     */
    private Boolean isdeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.URL
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.Email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.RecyclingReason
     *
     * @mbg.generated
     */
    private String recyclingreason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.CustomerType
     *
     * @mbg.generated
     */
    private String customertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.Fax
     *
     * @mbg.generated
     */
    private String fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.LastEffectRuleTime
     *
     * @mbg.generated
     */
    private Date lasteffectruletime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Customer.DataCircleID
     *
     * @mbg.generated
     */
    private Integer datacircleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.Name
     *
     * @return the value of Customer.Name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.Name
     *
     * @param name the value for Customer.Name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.NameSpell
     *
     * @return the value of Customer.NameSpell
     *
     * @mbg.generated
     */
    public String getNamespell() {
        return namespell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.NameSpell
     *
     * @param namespell the value for Customer.NameSpell
     *
     * @mbg.generated
     */
    public void setNamespell(String namespell) {
        this.namespell = namespell == null ? null : namespell.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.CustomerNo
     *
     * @return the value of Customer.CustomerNo
     *
     * @mbg.generated
     */
    public String getCustomerno() {
        return customerno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.CustomerNo
     *
     * @param customerno the value for Customer.CustomerNo
     *
     * @mbg.generated
     */
    public void setCustomerno(String customerno) {
        this.customerno = customerno == null ? null : customerno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.Address
     *
     * @return the value of Customer.Address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.Address
     *
     * @param address the value for Customer.Address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.Tel
     *
     * @return the value of Customer.Tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.Tel
     *
     * @param tel the value for Customer.Tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.Level
     *
     * @return the value of Customer.Level
     *
     * @mbg.generated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.Level
     *
     * @param level the value for Customer.Level
     *
     * @mbg.generated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.Industry
     *
     * @return the value of Customer.Industry
     *
     * @mbg.generated
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.Industry
     *
     * @param industry the value for Customer.Industry
     *
     * @mbg.generated
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.SubIndustry
     *
     * @return the value of Customer.SubIndustry
     *
     * @mbg.generated
     */
    public String getSubindustry() {
        return subindustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.SubIndustry
     *
     * @param subindustry the value for Customer.SubIndustry
     *
     * @mbg.generated
     */
    public void setSubindustry(String subindustry) {
        this.subindustry = subindustry == null ? null : subindustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.Source
     *
     * @return the value of Customer.Source
     *
     * @mbg.generated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.Source
     *
     * @param source the value for Customer.Source
     *
     * @mbg.generated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.Remark
     *
     * @return the value of Customer.Remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.Remark
     *
     * @param remark the value for Customer.Remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.OwnerID
     *
     * @return the value of Customer.OwnerID
     *
     * @mbg.generated
     */
    public Integer getOwnerid() {
        return ownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.OwnerID
     *
     * @param ownerid the value for Customer.OwnerID
     *
     * @mbg.generated
     */
    public void setOwnerid(Integer ownerid) {
        this.ownerid = ownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.HighSeasID
     *
     * @return the value of Customer.HighSeasID
     *
     * @mbg.generated
     */
    public String getHighseasid() {
        return highseasid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.HighSeasID
     *
     * @param highseasid the value for Customer.HighSeasID
     *
     * @mbg.generated
     */
    public void setHighseasid(String highseasid) {
        this.highseasid = highseasid == null ? null : highseasid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.ClaimTime
     *
     * @return the value of Customer.ClaimTime
     *
     * @mbg.generated
     */
    public Date getClaimtime() {
        return claimtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.ClaimTime
     *
     * @param claimtime the value for Customer.ClaimTime
     *
     * @mbg.generated
     */
    public void setClaimtime(Date claimtime) {
        this.claimtime = claimtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.ExpireTime
     *
     * @return the value of Customer.ExpireTime
     *
     * @mbg.generated
     */
    public Date getExpiretime() {
        return expiretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.ExpireTime
     *
     * @param expiretime the value for Customer.ExpireTime
     *
     * @mbg.generated
     */
    public void setExpiretime(Date expiretime) {
        this.expiretime = expiretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.JoinHighSeasTime
     *
     * @return the value of Customer.JoinHighSeasTime
     *
     * @mbg.generated
     */
    public Date getJoinhighseastime() {
        return joinhighseastime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.JoinHighSeasTime
     *
     * @param joinhighseastime the value for Customer.JoinHighSeasTime
     *
     * @mbg.generated
     */
    public void setJoinhighseastime(Date joinhighseastime) {
        this.joinhighseastime = joinhighseastime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.Status
     *
     * @return the value of Customer.Status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.Status
     *
     * @param status the value for Customer.Status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.ResaleCount
     *
     * @return the value of Customer.ResaleCount
     *
     * @mbg.generated
     */
    public Integer getResalecount() {
        return resalecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.ResaleCount
     *
     * @param resalecount the value for Customer.ResaleCount
     *
     * @mbg.generated
     */
    public void setResalecount(Integer resalecount) {
        this.resalecount = resalecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.CreatorID
     *
     * @return the value of Customer.CreatorID
     *
     * @mbg.generated
     */
    public Integer getCreatorid() {
        return creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.CreatorID
     *
     * @param creatorid the value for Customer.CreatorID
     *
     * @mbg.generated
     */
    public void setCreatorid(Integer creatorid) {
        this.creatorid = creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.CreateTime
     *
     * @return the value of Customer.CreateTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.CreateTime
     *
     * @param createtime the value for Customer.CreateTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.UpdatorID
     *
     * @return the value of Customer.UpdatorID
     *
     * @mbg.generated
     */
    public Integer getUpdatorid() {
        return updatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.UpdatorID
     *
     * @param updatorid the value for Customer.UpdatorID
     *
     * @mbg.generated
     */
    public void setUpdatorid(Integer updatorid) {
        this.updatorid = updatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.UpdateTime
     *
     * @return the value of Customer.UpdateTime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.UpdateTime
     *
     * @param updatetime the value for Customer.UpdateTime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.FilingCheckerID
     *
     * @return the value of Customer.FilingCheckerID
     *
     * @mbg.generated
     */
    public Integer getFilingcheckerid() {
        return filingcheckerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.FilingCheckerID
     *
     * @param filingcheckerid the value for Customer.FilingCheckerID
     *
     * @mbg.generated
     */
    public void setFilingcheckerid(Integer filingcheckerid) {
        this.filingcheckerid = filingcheckerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.DealStatus
     *
     * @return the value of Customer.DealStatus
     *
     * @mbg.generated
     */
    public Integer getDealstatus() {
        return dealstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.DealStatus
     *
     * @param dealstatus the value for Customer.DealStatus
     *
     * @mbg.generated
     */
    public void setDealstatus(Integer dealstatus) {
        this.dealstatus = dealstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.TradeTotalMoney
     *
     * @return the value of Customer.TradeTotalMoney
     *
     * @mbg.generated
     */
    public BigDecimal getTradetotalmoney() {
        return tradetotalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.TradeTotalMoney
     *
     * @param tradetotalmoney the value for Customer.TradeTotalMoney
     *
     * @mbg.generated
     */
    public void setTradetotalmoney(BigDecimal tradetotalmoney) {
        this.tradetotalmoney = tradetotalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.PaymentTotalMoney
     *
     * @return the value of Customer.PaymentTotalMoney
     *
     * @mbg.generated
     */
    public BigDecimal getPaymenttotalmoney() {
        return paymenttotalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.PaymentTotalMoney
     *
     * @param paymenttotalmoney the value for Customer.PaymentTotalMoney
     *
     * @mbg.generated
     */
    public void setPaymenttotalmoney(BigDecimal paymenttotalmoney) {
        this.paymenttotalmoney = paymenttotalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.RefundTotalMoney
     *
     * @return the value of Customer.RefundTotalMoney
     *
     * @mbg.generated
     */
    public BigDecimal getRefundtotalmoney() {
        return refundtotalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.RefundTotalMoney
     *
     * @param refundtotalmoney the value for Customer.RefundTotalMoney
     *
     * @mbg.generated
     */
    public void setRefundtotalmoney(BigDecimal refundtotalmoney) {
        this.refundtotalmoney = refundtotalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.TakeBackTime
     *
     * @return the value of Customer.TakeBackTime
     *
     * @mbg.generated
     */
    public Date getTakebacktime() {
        return takebacktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.TakeBackTime
     *
     * @param takebacktime the value for Customer.TakeBackTime
     *
     * @mbg.generated
     */
    public void setTakebacktime(Date takebacktime) {
        this.takebacktime = takebacktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.DealTime
     *
     * @return the value of Customer.DealTime
     *
     * @mbg.generated
     */
    public Date getDealtime() {
        return dealtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.DealTime
     *
     * @param dealtime the value for Customer.DealTime
     *
     * @mbg.generated
     */
    public void setDealtime(Date dealtime) {
        this.dealtime = dealtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.OldOwnerID
     *
     * @return the value of Customer.OldOwnerID
     *
     * @mbg.generated
     */
    public Integer getOldownerid() {
        return oldownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.OldOwnerID
     *
     * @param oldownerid the value for Customer.OldOwnerID
     *
     * @mbg.generated
     */
    public void setOldownerid(Integer oldownerid) {
        this.oldownerid = oldownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.OpportunityTotalMoney
     *
     * @return the value of Customer.OpportunityTotalMoney
     *
     * @mbg.generated
     */
    public BigDecimal getOpportunitytotalmoney() {
        return opportunitytotalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.OpportunityTotalMoney
     *
     * @param opportunitytotalmoney the value for Customer.OpportunityTotalMoney
     *
     * @mbg.generated
     */
    public void setOpportunitytotalmoney(BigDecimal opportunitytotalmoney) {
        this.opportunitytotalmoney = opportunitytotalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.LastFollowTime
     *
     * @return the value of Customer.LastFollowTime
     *
     * @mbg.generated
     */
    public Date getLastfollowtime() {
        return lastfollowtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.LastFollowTime
     *
     * @param lastfollowtime the value for Customer.LastFollowTime
     *
     * @mbg.generated
     */
    public void setLastfollowtime(Date lastfollowtime) {
        this.lastfollowtime = lastfollowtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.InputFieldNumber
     *
     * @return the value of Customer.InputFieldNumber
     *
     * @mbg.generated
     */
    public Integer getInputfieldnumber() {
        return inputfieldnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.InputFieldNumber
     *
     * @param inputfieldnumber the value for Customer.InputFieldNumber
     *
     * @mbg.generated
     */
    public void setInputfieldnumber(Integer inputfieldnumber) {
        this.inputfieldnumber = inputfieldnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.LastTradeMoney
     *
     * @return the value of Customer.LastTradeMoney
     *
     * @mbg.generated
     */
    public BigDecimal getLasttrademoney() {
        return lasttrademoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.LastTradeMoney
     *
     * @param lasttrademoney the value for Customer.LastTradeMoney
     *
     * @mbg.generated
     */
    public void setLasttrademoney(BigDecimal lasttrademoney) {
        this.lasttrademoney = lasttrademoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.IndustryName
     *
     * @return the value of Customer.IndustryName
     *
     * @mbg.generated
     */
    public String getIndustryname() {
        return industryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.IndustryName
     *
     * @param industryname the value for Customer.IndustryName
     *
     * @mbg.generated
     */
    public void setIndustryname(String industryname) {
        this.industryname = industryname == null ? null : industryname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.OwnerChangedTime
     *
     * @return the value of Customer.OwnerChangedTime
     *
     * @mbg.generated
     */
    public Date getOwnerchangedtime() {
        return ownerchangedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.OwnerChangedTime
     *
     * @param ownerchangedtime the value for Customer.OwnerChangedTime
     *
     * @mbg.generated
     */
    public void setOwnerchangedtime(Date ownerchangedtime) {
        this.ownerchangedtime = ownerchangedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.HouseNo
     *
     * @return the value of Customer.HouseNo
     *
     * @mbg.generated
     */
    public String getHouseno() {
        return houseno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.HouseNo
     *
     * @param houseno the value for Customer.HouseNo
     *
     * @mbg.generated
     */
    public void setHouseno(String houseno) {
        this.houseno = houseno == null ? null : houseno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.Area
     *
     * @return the value of Customer.Area
     *
     * @mbg.generated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.Area
     *
     * @param area the value for Customer.Area
     *
     * @mbg.generated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.AreaFullName
     *
     * @return the value of Customer.AreaFullName
     *
     * @mbg.generated
     */
    public String getAreafullname() {
        return areafullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.AreaFullName
     *
     * @param areafullname the value for Customer.AreaFullName
     *
     * @mbg.generated
     */
    public void setAreafullname(String areafullname) {
        this.areafullname = areafullname == null ? null : areafullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.IsDeleted
     *
     * @return the value of Customer.IsDeleted
     *
     * @mbg.generated
     */
    public Boolean getIsdeleted() {
        return isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.IsDeleted
     *
     * @param isdeleted the value for Customer.IsDeleted
     *
     * @mbg.generated
     */
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.URL
     *
     * @return the value of Customer.URL
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.URL
     *
     * @param url the value for Customer.URL
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.Email
     *
     * @return the value of Customer.Email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.Email
     *
     * @param email the value for Customer.Email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.RecyclingReason
     *
     * @return the value of Customer.RecyclingReason
     *
     * @mbg.generated
     */
    public String getRecyclingreason() {
        return recyclingreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.RecyclingReason
     *
     * @param recyclingreason the value for Customer.RecyclingReason
     *
     * @mbg.generated
     */
    public void setRecyclingreason(String recyclingreason) {
        this.recyclingreason = recyclingreason == null ? null : recyclingreason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.CustomerType
     *
     * @return the value of Customer.CustomerType
     *
     * @mbg.generated
     */
    public String getCustomertype() {
        return customertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.CustomerType
     *
     * @param customertype the value for Customer.CustomerType
     *
     * @mbg.generated
     */
    public void setCustomertype(String customertype) {
        this.customertype = customertype == null ? null : customertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.Fax
     *
     * @return the value of Customer.Fax
     *
     * @mbg.generated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.Fax
     *
     * @param fax the value for Customer.Fax
     *
     * @mbg.generated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.LastEffectRuleTime
     *
     * @return the value of Customer.LastEffectRuleTime
     *
     * @mbg.generated
     */
    public Date getLasteffectruletime() {
        return lasteffectruletime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.LastEffectRuleTime
     *
     * @param lasteffectruletime the value for Customer.LastEffectRuleTime
     *
     * @mbg.generated
     */
    public void setLasteffectruletime(Date lasteffectruletime) {
        this.lasteffectruletime = lasteffectruletime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Customer.DataCircleID
     *
     * @return the value of Customer.DataCircleID
     *
     * @mbg.generated
     */
    public Integer getDatacircleid() {
        return datacircleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Customer.DataCircleID
     *
     * @param datacircleid the value for Customer.DataCircleID
     *
     * @mbg.generated
     */
    public void setDatacircleid(Integer datacircleid) {
        this.datacircleid = datacircleid;
    }
}