package com.deppon.test05.dao;

import com.deppon.test05.entity.CustomerEntity;
import com.deppon.test05.entity.CustomerEntityKey;

public interface CustomerEntityMapper extends IEntityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Customer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(CustomerEntityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Customer
     *
     * @mbg.generated
     */
    int insert(CustomerEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Customer
     *
     * @mbg.generated
     */
    int insertSelective(CustomerEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Customer
     *
     * @mbg.generated
     */
    CustomerEntity selectByPrimaryKey(CustomerEntityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CustomerEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CustomerEntity record);
}